name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: great
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-great: August
      - name: Simple JS Action
        run: echo "${{ steps.greet.outputs.time }}"